server:
  host: "localhost"
  port: "8080"
  mode: "debug"  # debug, release, test

database:
  driver: "sqlite3"
  dsn: "./data/go-springAi.db"

jwt:
  secret: "your-secret-key-change-this-in-production"
  expire_time: 24  # hours

openai:
  api_key: "sk-mock-api-key-for-development-testing-only"  # Mock API key for development
  base_url: "https://api.openai.com/v1"

googleai:
  api_key: "mock-google-ai-api-key-for-development"  # Mock API key for development