// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/gin-gonic/gin"
	"go-springAi/internal/config"
	"go-springAi/internal/controllers"
	"go-springAi/internal/database"
	"go-springAi/internal/dto"
	"go-springAi/internal/errors"
	"go-springAi/internal/i18n"
	"go-springAi/internal/provider"
	"go-springAi/internal/repository"
	"go-springAi/internal/service"
	"go-springAi/internal/utils"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序
func InitializeApp(configPath string) (*App, func(), error) {
	config, err := ProvideConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	db, err := ProvideDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	jwtManager := ProvideJWTManager(config)
	manager, err := ProvideI18nManager()
	if err != nil {
		return nil, nil, err
	}
	errorHandler := ProvideErrorHandler(manager)
	customValidator := utils.NewCustomValidator()
	repositoryManager := repository.NewRepositoryManager(db)
	mcpService := ProvideMCPService(repositoryManager, logger)
	openAIService := ProvideOpenAIService(config, logger)
	googleAIService, err := ProvideGoogleAIService(config, logger)
	if err != nil {
		return nil, nil, err
	}
	apiKeyService := ProvideAPIKeyService(repositoryManager)
	internalMCPClient := ProvideInternalMCPClient(mcpService)
	stockAnalysisService := ProvideStockAnalysisService(internalMCPClient, logger)
	providerManager := ProvideProviderManager(openAIService, googleAIService, logger)
	aiAssistantService := ProvideAIAssistantService(mcpService, openAIService, providerManager, stockAnalysisService, logger)
	mcpController := ProvideMCPController(mcpService, logger, errorHandler)
	aiAssistantController := ProvideAIAssistantController(aiAssistantService, logger, errorHandler)
	testI18nController := ProvideTestI18nController()
	stockController := ProvideStockController(stockAnalysisService, logger, errorHandler)
	aiController := ProvideAIController(providerManager, apiKeyService, logger, errorHandler)
	engine := ProvideRouter(logger, jwtManager, mcpController, aiController, aiAssistantController, stockController, testI18nController, manager)
	app, cleanup := NewApp(config, logger, db, jwtManager, manager, errorHandler, customValidator, repositoryManager, mcpService, openAIService, googleAIService, apiKeyService, stockAnalysisService, aiAssistantService, mcpController, aiAssistantController, testI18nController, stockController, providerManager, aiController, engine)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App 应用程序结构
type App struct {
	Config                *config.Config
	Logger                *zap.Logger
	DB                    *database.DB
	JWTManager            *utils.JWTManager
	I18nManager           *i18n.Manager
	ErrorHandler          *errors.ErrorHandler
	Validator             *utils.CustomValidator
	RepoManager           repository.RepositoryManager
	MCPService            service.MCPService
	OpenAIService         *service.OpenAIService
	GoogleAIService       *service.GoogleAIService
	APIKeyService         service.APIKeyService
	StockAnalysisService  *service.StockAnalysisService
	AIAssistantService    *service.AIAssistantService
	MCPController         *controllers.MCPController
	AIAssistantController *controllers.AIAssistantController
	TestI18nController    *controllers.TestI18nController
	StockController       *controllers.StockController
	ProviderManager       *provider.Manager
	AIController          *controllers.AIController
	Router                *gin.Engine
}

// NewApp 创建应用程序实例
func NewApp(config2 *config.Config,
	logger *zap.Logger,
	db *database.DB,
	jwtManager *utils.JWTManager,
	i18nManager *i18n.Manager,
	errorHandler *errors.ErrorHandler,
	validator *utils.CustomValidator,
	repoManager repository.RepositoryManager,
	mcpService service.MCPService,
	openaiService *service.OpenAIService,
	googleaiService *service.GoogleAIService,
	apiKeyService service.APIKeyService,
	stockAnalysisService *service.StockAnalysisService,
	aiAssistantService *service.AIAssistantService,
	mcpController *controllers.MCPController,
	aiAssistantController *controllers.AIAssistantController,
	testI18nController *controllers.TestI18nController,
	stockController *controllers.StockController,
	providerManager *provider.Manager,
	aiController *controllers.AIController,
	router *gin.Engine,
) (*App, func()) {
	app := &App{
		Config:                config2,
		Logger:                logger,
		DB:                    db,
		JWTManager:            jwtManager,
		I18nManager:           i18nManager,
		ErrorHandler:          errorHandler,
		Validator:             validator,
		RepoManager:           repoManager,
		MCPService:            mcpService,
		OpenAIService:         openaiService,
		GoogleAIService:       googleaiService,
		APIKeyService:         apiKeyService,
		StockAnalysisService:  stockAnalysisService,
		AIAssistantService:    aiAssistantService,
		MCPController:         mcpController,
		AIAssistantController: aiAssistantController,
		TestI18nController:    testI18nController,
		StockController:       stockController,
		ProviderManager:       providerManager,
		AIController:          aiController,
		Router:                router,
	}

	app.initializeMCPSystem()

	cleanup := func() {
		if app.DB != nil {
			app.DB.Close()
		}
		if app.Logger != nil {
			app.Logger.Sync()
		}
	}

	return app, cleanup
}

// initializeMCPSystem 自动初始化MCP系统
func (app *App) initializeMCPSystem() {
	if app.MCPService == nil {
		app.Logger.Warn("MCP service is not available, skipping auto-initialization")
		return
	}

	initReq := &dto.MCPInitializeRequest{
		ProtocolVersion: "2024-11-05",
		Capabilities: dto.MCPCapabilities{
			Tools: &dto.MCPToolsCapability{
				ListChanged: true,
			},
			Logging: &dto.MCPLoggingCapability{},
		},
		ClientInfo: dto.MCPClientInfo{
			Name:    "Auto-initialized MCP Server",
			Version: "1.0.0",
		},
	}

	ctx := context.Background()

	response, err := app.MCPService.Initialize(ctx, initReq)
	if err != nil {
		app.Logger.Error("Failed to auto-initialize MCP system", zap.Error(err), zap.String("module", "startup"), zap.String("operation", "mcp_auto_init"))
		return
	}

	app.Logger.Info("MCP system auto-initialized successfully", zap.String("protocolVersion", response.ProtocolVersion), zap.String("serverName", response.ServerInfo.Name), zap.String("serverVersion", response.ServerInfo.Version), zap.String("module", "startup"), zap.String("operation", "mcp_auto_init"))
}
